version: '3'

volumes:
  pg_data_local:
  static_local:

services:

  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_local:/var/lib/postgresql/data

  backend:
    build: ./backend/
    env_file: .env
    depends_on:
      - db
    volumes:
      - static_local:/backend_static

  frontend:
    env_file: .env
    build: ./frontend/
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_local:/frontend_static

  gateway:
    build: ./gateway/
    depends_on:
      - backend
    volumes:
      - static_local:/staticfiles/
    ports:
      - 8000:80
